<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Condorcet Method</title>
</head>
<body>
    <h1>Condorcet Method for Moral Values</h1>
    <button onclick="startApp()">Start</button>
    <div id="results"></div>

    <script>
        function startApp() {
            const moralValues = inputMoralValues();
            const pairwisePreferences = getPairwisePreferences(moralValues);
            const sortedValues = condorcetMethod(pairwisePreferences);
            displayResults(sortedValues);
        }

        function inputMoralValues() {
            let numValues = prompt("How many moral values would you like to input?");
            numValues = parseInt(numValues);
            const values = [];

            for (let i = 0; i < numValues; i++) {
                const value = prompt(`Enter moral value ${i + 1}:`);
                values.push(value);
            }
            return values;
        }

        function getPairwisePreferences(values) {
            const pairwisePreferences = {};

            for (let i = 0; i < values.length; i++) {
                for (let j = i + 1; j < values.length; j++) {
                    const pair = [values[i], values[j]];
                    const preference = prompt(`Which is more important?\n1. ${pair[0]}\n2. ${pair[1]}\nEnter 1 or 2:`);
                    if (!pairwisePreferences[pair[0]]) pairwisePreferences[pair[0]] = 0;
                    if (!pairwisePreferences[pair[1]]) pairwisePreferences[pair[1]] = 0;

                    if (preference === '1') {
                        pairwisePreferences[pair[0]] += 1;
                    } else if (preference === '2') {
                        pairwisePreferences[pair[1]] += 1;
                    }
                }
            }
            return pairwisePreferences;
        }

        function condorcetMethod(pairwisePreferences) {
            const sortedValues = Object.entries(pairwisePreferences)
                .sort((a, b) => b[1] - a[1])
                .map(entry => entry[0]);
            return sortedValues;
        }

        function displayResults(sortedValues) {
            let resultText = "<h2>Organized Moral Values (Condorcet Method):</h2><ul>";
            sortedValues.forEach((value, index) => {
                resultText += `<li>${index + 1}. ${value}</li>`;
            });
            resultText += "</ul>";
            document.getElementById("results").innerHTML = resultText;
        }
    </script>
</body>
</html>
